import { Inter } from "next/font/google";
import { ClerkProvider,ClerkLoaded,ClerkLoading } from '@clerk/nextjs'
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ClerkLoading>
          <div className="text-center text-xl mx-auto mt-4">
          Loading...
          </div>
        </ClerkLoading>
        <ClerkLoaded>
      <Navbar/>
        {children}
        </ClerkLoaded>
        </body>
    </html>
    </ClerkProvider>
  );
}
